modLoader="javafml"
loaderVersion="[31.1,)"
issueTrackerURL="https://github.com/LogicTechCorp/LibraryEx/issues"

[[mods]]
modId="libraryex"
version="${file.jarVersion}"
displayName="LibraryEx"
displayURL="https://minecraft.curseforge.com/projects/libraryex"
logoFile="assets/libraryex/textures/logo.png"
authors="LogicTechCorp"
description="A library for mods that add expansions, explorations, and experiences to Minecraft."

[[dependencies.libraryex]]
modId="forge"
mandatory=true
versionRange="[31.1.37,)"
ordering="NONE"
side="BOTH"
